name: PHP Syntax Check

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['5.6']

    steps:
    - uses: actions/checkout@v1

    - name: Use PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}

    - name: php check syntax
      run: |
        if [[ $(find . -iname '*.php' -exec php -l '{}' \; | grep '^No syntax errors' -v  | sed  -Ez '$ s/\n+$//') != "" ]]; then exit 1; fi
