name: PHP Syntax

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['5.3']

    steps:
    - uses: actions/checkout@v1

    - name: Use PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.node-version }}

    - name: php check syntax
      run: |
        find . -iname '*.php' -exec php -l '{}' \; | grep '^No syntax errors' -v  | less
